version: "3"
services:
  app:
    build: .
    command: sh -c "node app.js"
    volumes:
      - .:/app
      - node_modules_data:/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
volumes:
  node_modules_data:
